In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
b = np.array([[3, 2, 1], [3, 2, 1], [3, 2, 1]])
print(a)
print(b)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[3 2 1]
 [3 2 1]
 [3 2 1]]


In [3]:
#TODO:计算a,b的矩阵乘结果，并输出
ab = np.matmul(a, b)
print(ab)

[[18 12  6]
 [18 12  6]
 [18 12  6]]


In [4]:
#TODO：将结果转换回Python List形式，并输出
ab_list = ab.tolist()
print(ab_list)

[[18, 12, 6], [18, 12, 6], [18, 12, 6]]
